# Generated by Django 5.2.12 on 2026-03-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
